### ISSUE TITLE
"Clean mods" option

### ISSUE THREAD

**Issue by Dragon-32** [Gribbleshnibit8/xcom2-launcher#5]
Saw over on Reddit (not a member) that you're unclear on what the Clean Mods option does. I think I can help (a bit).

I had some discussions with Solariz / Solaris etc. over on Nexus about the mod launcher, think that was the first place he started to talk about the alternative mod launcher.

I believe, I haven't used the function myself, this is what it does:

**Clean Mods > Source Files**
Cleans out the contents of a mod's SRC directory.
_Options_
None - Don't clean
XComGame - Delete the ~16MB of vanilla game source code included, I believe by default, when a mod is packaged up in ModBuddy. Including these files does nothing apart from bloat the download.
All - Delete all files in the SRC directory. Not sure if also removes the directory tree. Contents of SRC directory not referenced by the game (these are uncompiled source code files, game uses .u files in \Source

**Clean Mods > ModShaderCache files**
Deletes <mod folder>\Content\<mod name>_ModShaderCache.upk
_Options_
None - Don't clean
Empty - Delete if file size = 1KB (i.e. empty)
All - Delete all files which match the file name mask

Idea behind the ModShaderCache was to reduce mod bloat, you used to get voice packs with ~80MB *_ModShaderCache.upk files before Firaxis / 2K fixed ModBuddy.

Don't think there's a file size check so it can delete shader caches which are actually needed when the All option is selected, so any mods _needing_ the file (all those cosmetics) will be a collection of black models.

See this thread: https://forums.nexusmods.com/index.php?/topic/3886390-looking-for-a-way-to-skip-the-launcher/

Personally, I'd keep the SRC cleanup and drop the ModShaderCache.

**Comment by robojumper** [comment]
The "ModShaderCache: All" thing should definitely be dropped, because it's basically just a noob-trap for people to break their mod installs. About the 371 Bytes ones, it probably doesn't matter because 371 bytes is really nothing even if you have thousands of mods. I'd say get rid of it too.
