### ISSUE TITLE
Can't download version 1.0.0

### ISSUE THREAD

**Issue by Littlebob86** [Gribbleshnibit8/xcom2-launcher#8]
Hey!

You're a life saver for creating this! I've been using it for ages, but I did a new re-install for LW2, and released that you did an update. Anyway, so I keep getting the message that there's an update https://github.com/Gribbleshnibit8/xcom2-launcher/releases/tag/v1.0.0 but when I go there it says release 1.0.0, although the download links are only for version 0.5.0, and I've used 2 different links and when I launch the alternate mod manager, I get a notification saying there's an update which takes me back to that site! :(

I mean, the changes you state (With the run xcom at the top) are present and the launcher works fine, but I'm just super confused and keen to have the latest version :)

![github](https://cloud.githubusercontent.com/assets/25976048/23252728/dce1ac34-f9ec-11e6-993e-d24906989bb6.jpg)

**Comment by Littlebob86** [comment]
![github 2](https://cloud.githubusercontent.com/assets/25976048/23252831/257f07f2-f9ed-11e6-9fe3-f059276e5e3e.jpg)

**Comment by robojumper** [comment]
This has already been reported and will be fixed. #3
